version: '3.7'
services:
  builder:
    build: ./builder
    # dockerfile: Dockerfile-maven
    # image: builder:latest
    volumes:
       # - . :/build
       - share:/build
  web:
    build: ./web
    depends_on:
      - builder
    ports:
        - '8081:8080'
    volumes:
        - share:/opt/tomcat/webapps/
volumes:
  share: {}