version: '3.7'
services:
  builder:
    build: ./builder
    # dockerfile: Dockerfile-maven
    volumes:
       - share:/build
  web:
    # build: ./web
    image: tomcat:8.5-alpine
    depends_on:
      - builder
    ports:
        - '8081:8080'
    volumes:
        # - share:/opt/tomcat/webapps/
        -  share:/usr/local/tomcat/webapps/
volumes:
  share: {}
